generate_modules:
  output_file: output/crew_modules_output.txt
  description: >
    # Objectives

    As a Learning Experience Designer at General Assembly you develop courses using competency-based learning.

    Your task is to develop the modules for a course based on the competencies and other inputs you were provided.

    A module is a single unit of learning that is associated with a single competency. Competencies typically contain multiple modules.

    Modules can either be lectures or lab work.

    Lecture modules are *typically* 60-90 minutes long, but may be longer or shorter, depending on the topic.

    You will also explain your rationale, which must detail how each module teaches the competencies, and fulfills the course and learning outcomes and client priorities in a way that's appropriate for the learner persona. Keep the rationale concise and to the point.

    You must use the following inputs (denoted by the <inputs> tag) to develop the modules:

    <inputs>
    The competencies: {competencies}

    The course description: {course_description}

    The course's business outcomes: {course_business_outcomes}

    The client's priorities: {client_priorities}

    The primary learner persona job role: {primary_persona_job_role}

    The learner persona description: {learner_persona_description}

    The learner persona attributes and background: {learner_persona_attributes_and_background}

    The learner persona's existing foundational knowledge related to the course topic (to be used as pre-requisites for the course): {learner_persona_existing_knowledge}

    The high-level learning outcomes of the course: {course_learning_outcomes}

    The software and tools that will be used in the course: {course_software_and_tools}
    </inputs>

    ## Developing modules

    Modules are the building blocks of a course. They are the units of learning that are tied to a single competency.

    Modules represent the component parts or steps required to achieve a single competency. Those steps require the application of various skills and knowledge to meet the competency's learning outcomes.

    By extension, modules in a course should generally build on each other - don't skip important topics, or have students complete labs when they haven't yet learned the necessary skills.

    Modules should always focus on hard skills. If soft-skills will never be the focus of the entirety of a module.

    ## Example modules and how they relate to competencies

    Here are a couple of examples:

    Competency: Build a full-stack web app with authentication and CRUD operations.

    This is a larger competency (totalling 2400 minutes).

    Modules associated with this competency:

    - Intro to Node
    - Intro to Express
    - Intro to Express Lab
    - RESTful Routing
    - Exposing an API
    - EJS
    - EJS Lab
    - Intro to Databases
    - Environment Variables
    - Building a MEN Stack CRUD App
    - Building a MEN Stack CRUD App Lab
    - Mongoose Relationships
    - Mongoose Relationships Lab
    - MEN Stack Session Authentication

    Competency: User Research

    This is a smaller competency (totalling 480 minutes).

    - UX Research Approaches & Methods
    - UX Research Approaches & Methods Workshop 
    - UX Research Synthesis
    - UX Research Synthesis Workshop

    ## Module titles

    Modules titles should be concise and are written in AP Style title case.

    Module titles should not exceed 40 characters.

    Lectures will never include the word "Lecture" in the title. Technical courses include Labs will always end with "Lab". Non-technical courses include Workshops the word "Workshop" in the title.

    Note from the examples above that the module titles should include the specific technologies used in a module - for example if a module focuses on JavaScript or JavaScript concepts then the title should include "JavaScript".

    ## Module overview

    Each module will have a single paragraph (at least 3 sentences) overview that describes the module's content.

    This overview is student-facing and should be provide a high-level overview of the module's content.

    ## Module time estimates

    Time estimates should be provided in minutes. Modules are typically 60-90 minutes long, but may be longer or shorter, depending on the topic. Modules will be delivered live in a classroom setting, so leave time for student questions and discussion along the way.

    It is natural for some modules to take longer than others. Attempt to make each time estimate a multiple of 15 minutes.

    ## Context

    When writing student-facing copy, you should use the following context:

    <voice id=1 title="Voice" purpose="This critical document outlines the best practices for writing content. It provides guidelines for writing clear, accurate, and engaging content that is tailored to the broad needs of a audience.">
    {doc_voice}
    </voice>

  expected_output: >
    A set of competencies for the crew to use in developing a competency map 
    formatted in JSON with the following structure:

    {
      "competencies": [
        {
          "competency": "A single competency - matching the input data",
          "time_estimate_m": An integer representing the time it will take to deliver the competency in minutes. This should match the time estimate for the competency in the input data.
          "rationale": "Explain the purpose of including this competency in relation to the input you were provided. Again, this should match the rationale for the competency in the input data."
          "modules": [
            {
              "title": "",
              "overview": "",
              "time_estimate_m": ""
              "type": "lecture" | "lab"
              "rationale": "Explain the purpose of including this module in relation to the input you were provided."
              "tools_and_technologies": [
                "A list of tools and technologies used in the module. Only include tools and technologies that are relevant to the module's content. Do not include any tools or software that are not present in the input data."
              ]
            }
          ]
        }
      ]
    }

    You should only output a JSON object. Never output markdown. NO MARKDOWN.
  agent: led

qa_modules:
  output_file: output/crew_modules_qa_output.txt
  description: >
    # Objectives

    As a Learning Experience Designer at General Assembly you develop courses using competency-based learning.

    Your task is to review the generated modules and provide quality assurance work to ensure the modules are aligned with the competencies and other inputs you're provided.

    Do not make suggestions related to what students should do in the module - focus on auditing the data received from the previous agent.

    Do not build a "checklist" of targets met. You should only provide feedback on changes that are necessary to meet the client's priorities and course business outcomes.

    You must use the following inputs (denoted by the <inputs> tag) to review the modules:

    <inputs>
    The generated module output from the previous task.

    The course description: {course_description}

    The course's business outcomes: {course_business_outcomes}

    The client's priorities: {client_priorities}

    The primary learner persona job role: {primary_persona_job_role}

    The learner persona description: {learner_persona_description}

    The learner persona attributes and background: {learner_persona_attributes_and_background}

    The learner persona's existing foundational knowledge related to the course topic (to be used as pre-requisites for the course): {learner_persona_existing_knowledge}

    The high-level learning outcomes of the course: {course_learning_outcomes}

    The software and tools that will be used in the course: {course_software_and_tools}
    </inputs>

    ## Background on modules

    Modules are the building blocks of a course. They are the units of learning that are tied to a single competency.

    Modules represent the component parts or steps required to achieve a single competency. Those steps require the application of various skills and knowledge to meet the competency's learning outcomes.

    By extension, modules in a course should generally build on each other - don't skip important topics, or have students complete labs when they haven't yet learned the necessary skills.

    Modules should always focus on hard skills. If soft-skills will never be the focus of the entirety of a module.

    ## Reviewing modules

    Take what you know about modules into account when you're reviewing them.

    You will only provide feedback on the module's content in the "qa_feedback" field of a module. Base your feedback on what you received from the previous agent. The rest of a module's details should be left as is. A human reviewer will make the final changes later.

    You should specifically check for the following:
    
    - The client's priorities should be addressed in the modules.
    - Modules should not lead with a soft-skill (for example - collaboration should not be the focus of any module, even if the client requests directly reference collaboration as a priority in the course).
    - Tool usage is appropriate for the module's content.
    - The module overview should be at least 3 sentences and use student-facing language that provides a high-level overview of the module's content.

    ## Module time estimates

    Time estimates should be provided in minutes. Modules are typically 60-90 minutes long, but may be longer or shorter, depending on the topic. Modules will be delivered live in a classroom setting, so leave time for student questions and discussion along the way.

    It is natural for some modules to take longer than others. Attempt to make each time estimate a multiple of 15 minutes.

    ## Context

    When writing student-facing copy, you should use the following context:

    <voice id=1 title="Voice" purpose="This critical document outlines the best practices for writing content. It provides guidelines for writing clear, accurate, and engaging content that is tailored to the broad needs of a audience.">
    {doc_voice}
    </voice>
    
  expected_output: >
    A set of competencies for the crew to use in developing a competency map 
    formatted in JSON with the following structure:

    {
      "competencies": [
        {
          "competency": "A single competency - matching the input data",
          "time_estimate_m": An integer representing the time it will take to deliver the competency in minutes. This should match the time estimate for the competency in the input data.
          "rationale": "Explain the purpose of including this competency in relation to the input you were provided. Again, this should match the rationale for the competency in the input data."
          "modules": [
            {
              "title": "",
              "overview": "",
              "time_estimate_m": ""
              "type": "lecture" | "lab"
              "rationale": "Explain the purpose of including this module in relation to the input you were provided."
              "tools_and_technologies": [
                "A list of tools and technologies used in the module. Only include tools and technologies that are relevant to the module's content. Do not include any tools or software that are not present in the input data."
              ]
              "qa_feedback": "A list of suggestions for the module's content. Only include suggestions for the module's content. Do not include any suggestions for the module's time estimate or type."
            }
          ]
        }
      ]
    }

    You should only output a JSON object. Never output markdown. NO MARKDOWN.
  agent: led_qa
