generate_modules:
  description: >
    # Objectives

    As a Learning Experience Designer at General Assembly you develop courses using competency-based learning.

    Your task is to develop the modules for a course based on the competencies and other inputs you were provided.

    A module is a single unit of learning that is associated with a single competency. Competencies typically contain multiple modules.

    Modules can either be lectures or lab work.

    Lecture modules are *typically* 60-90 minutes long, but may be longer or shorter, depending on the topic. 

    You will also explain your reasoning for including each module, which will be used to justify your choices to human reviewers. Only include details specific to the inputs you were provided - you don't need to justify the module itself. Keep the rationale concise and to the point.

    You must use the following inputs (denoted by the <inputs> tag) to develop the modules:

    <inputs>
    The competencies: {competencies}

    The course description: {course_description}

    The course's business outcomes: {course_business_outcomes}

    The client's priorities: {client_priorities}

    The primary learner persona job role: {primary_persona_job_role}

    The learner persona description: {learner_persona_description}

    The learner persona attributes and background: {learner_persona_attributes_and_background}

    The learner persona's existing foundational knowledge related to the course topic (to be used as pre-requisites for the course): {learner_persona_existing_knowledge}

    The high-level learning outcomes of the course: {course_learning_outcomes}

    The software and tools that will be used in the course: {course_software_and_tools}
    </inputs>

    

  expected_output: >
    A set of competencies for the crew to use in developing a competency map 
    formatted in JSON with the following structure:

    {
      "competencies": [
        {
          "competency": "A single competency - matching the input data",
          "time_estimate_m": An integer representing the time it will take to deliver the competency in minutes. This should match the time estimate for the competency in the input data.
          "rationale": "Explain the purpose of including this competency in relation to the input you were provided. Again, this should match the rationale for the competency in the input data."
          "modules": [
            {
            
            }
          ]
        }
      ]
    }

    You should only output a JSON object. Never output markdown. NO MARKDOWN.
  agent: led
