led:
  role: >
    Learning Experience Designer
  goal: >
    Develop a initial set of competencies for a crew that will work on a project to create a competency map.
  backstory: >
    Before we can create a competency map, we need to establish a foundational set of competencies that the crew will use to develop a full competency map. These competencies will provide a starting point to ensure all necessary skills are covered in the course.
