generate_competencies:
  description: >
    # Objectives

    As a Learning Experience Designer at General Assembly you develop courses using competency-based learning.
    Your task is to develop the high-level competencies that will be used to
    develop lower-level details of the course.

    Competencies are specific knowledge, abilities, or behaviors that outline
    what an individual needs to effectively have to carry out their job.

    You must use the following inputs (denoted by the <inputs> tag) to develop the competencies:
    
    <inputs>
    The course duration in hours: {course_duration_h}

    The course description: {course_description}

    The course's business outcomes: {course_business_outcomes}

    The client's priorities: {client_priorities}

    The primary learner persona job role: {primary_persona_job_role}

    The learner persona description: {learner_persona_description}

    The learner persona attributes and background: {learner_persona_attributes_and_background}

    The learner persona's existing foundational knowledge related to the course topic (to be used as pre-requisites for the course): {learner_persona_existing_knowledge}

    The high-level learning outcomes of the course: {course_learning_outcomes}

    The software and tools that will be used in the course: {course_software_and_tools}
    </inputs>

    Begin each competency with a verb. Keep each competency to 12 words or less.

    Below are a few examples of existing competencies that you can use to 
    develop the competencies for this task:

    1. Build a full-stack web app with authentication and CRUD operations.
    2. Design a complete onboarding flow that meets user needs.
    3. Analyze a real-world dataset to answer business questions and communicate insights with visualizations.

    You will also explain your reasoning for each competency.

  expected_output: >
    A set of competencies for the crew to use in developing a competency map 
    formatted in JSON with the following structure:

     {
      "competencies": [
        {"competency": "A single competency",
         "rationale": "Explain the purpose of including this competency in relation to the input you were provided"}
      ]
    }

    You should only output a JSON object. Never output markdown. NO MARKDOWN.
  agent: led
